// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbexdrnxqkugvtcmdwze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndiZXhkcm54cWt1Z3Z0Y21kd3plIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1OTQ5MTIsImV4cCI6MjA1MjE3MDkxMn0.1CgOlDO-bcWlucb_8jU0OcZHGiEw_wRiOdU-Za8b7x4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);